backend:
  name: github
  repo: lynly/design-system-sb-decap
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: 'public' # Media files will be stored in the repo under public/
public_folder: '/' # The src attribute for uploaded media will begin with /

collections:
  - name: "docs" # Used in routes, e.g., /admin/collections/blog
    label: "Docs" # Used in the UI
    folder: "src/components" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: mdx
    slug: '{{title}}' # Filename template, e.g., title.stories.mdx
    summary: '{{filename}}'
    format: yaml-frontmatter
    frontmatter_delimiter: ['/*', '*/']
    fields: # The fields for each document, usually in front matter
      - { label: 'Mdx imports', name: 'mdx-imports', widget: 'markdown', pattern: ['{/* title: {{title}} */}'], hint: 'imports, <Meta/>' } # TODO test custom
      - { label: "Title", name: "title", widget: "string", tagname: 'h1', pattern: ['{{title}}'] }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'DD MMMM YYYY', default: '{{now}}' }
      - { label: "Subtitle", name: "sub-title", widget: "markdown",  hint: '<Subtitle/>' } # TODO test custom
      - label: 'About Section'
        name: 'about-section'
        widget: 'object'
        fields:
              - { label: 'About heading', name: 'about-heading', widget: 'string', tagname: 'h2', pattern: ['About this component'] }
              - { label: 'About content', name: 'about-content', widget: 'text' }
              - { label: 'About MetaComponent', name: 'about-meta-component', widget: 'markdown',  hint: '<MetaComponent/>' } # TODO test custom
      - label: 'Example Section'
        name: 'example-section'
        widget: 'object'
        fields:
              - { label: 'Example heading', name: 'example-heading', widget: 'string', tagname: 'h3'}
              - { label: 'Example content', name: 'example-content', widget: 'text' }
              - { label: 'Example story', name: 'example-story', widget: 'markdown',  hint: '<Canvas/>' } # TODO test custom
      - label: 'Example Section 2'
        name: 'example-section-2'
        widget: 'object'
        required: false
        fields:
              - { label: 'Example heading', name: 'example-heading', widget: 'string', tagname: 'h3'}
              - { label: 'Example content', name: 'example-content', widget: 'text' }
              - { label: 'Example story', name: 'example-story', widget: 'markdown',  hint: '<Canvas/>' } # TODO test custom
      - label: 'Properties Section'
        name: 'properties-section'
        widget: 'object'
        fields:
              - { label: 'Properties', name: 'properties', widget: 'text', tagname: 'h2', pattern: ['Properties'] }
              - { label: 'Properties table', name: 'properties-table', widget: 'markdown',  hint: '<Controls/>' } # TODO test custom