backend:
  name: github
  repo: lynly/design-system-sb-decap
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: 'public' # Media files will be stored in the repo under public/
public_folder: '/' # The src attribute for uploaded media will begin with /

collections:
  - name: "docs" # Used in routes, e.g., /admin/collections/blog
    identifier_field: name
    label: "Docs" # Used in the UI
    folder: "src/components" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: mdx
    slug: '{{title}}' # Filename template, e.g., title.stories.mdx
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    format: yaml-frontmatter
    frontmatter_delimiter: ['/*', '*/']
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "hidden" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: 'Body', name: 'body', widget: 'markdown', modes: ['raw'] }
